/*

 PATTERN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\schuyler\projects\gameboy_dev\gb-test-screen-alignment\img\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __pattern_h_INCLUDE
#define __pattern_h_INCLUDE

#define patternWidth 20
#define patternHeight 18
#define patternBank 0

extern const unsigned char pattern[];

#endif

/* End of PATTERN.H */
